### ISSUE TITLE
circuitpy-tag: 8.2.3 or 8.2.0 fails

### ISSUE THREAD

**Issue by jake1164** [adafruit/build-mpy#7]
Compiling using circuitpy=tag: "8.0.3" works as expected but updating circuitpy-tag: "8.2.0" will fail with the message: 

Note: switching to '8.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5dc2b168d Merge pull request #8123 from jepler/issue8121-workaround
make: *** No rule to make target 'fetch-submodules'.  Stop.
Error: Process completed with exit code 2.

**Comment by dhalbert** [comment]
`make fetch-submodules` is now `make fetch-all-submodules` at the top level or `make fetch-port-submodules` in in a `ports/something` directory. See https://learn.adafruit.com/building-circuitpython/build-circuitpython#fetch-submodules-3141425

**Comment by jake1164** [comment]
Should it be backwards compatible or just made to work on >= 8.2.0 and a note put in documentation?

**Comment by tekktrik** [comment]
Closed per #8
